### ISSUE TITLE
bias_mri$T1: $ operator is invalid

### ISSUE THREAD

**Issue by jdwor** [DavidPayares/neuronorm#1]
Hi David,

Thanks so much for putting this awesome package together! I'm really excited to use it - it looks incredibly helpful. Just one small issue at this point. I'm getting an error at the following line of the preprocess_modalities function:

`bias_mris <- create_bias_list(modalities, bias_mri$T1, bias_mri_comp)`

It seems to be coming from the fact that the bias_mri that I'm getting at that point in the code is a matrix (two very long rows, one for each of the two modalities I've included), instead of the named list of images that create_bias_list seems to be expecting. The mapply-based line that creates 'bias_mri' seems to be working okay - it saves out nice bias corrected images to the directory - but instead of storing those images themselves in the bias_mri object it's just storing a big matrix.

Any thoughts on why this might be happening?

Thanks so much!
Jordan

**Comment by jdwor** [comment]
Upon further digging, it looks like adding "SIMPLIFY = FALSE" to the 'bias_mri <- mapply(....)' call turns the output into a named list of images instead of a matrix. And then the downstream 'create_bias_list' call works perfectly. Seems like an easy fix :)

**Comment by DavidPayares** [comment]
Hi Jordan,

Thank you for finding and solving the issue!
I'll update the function.

Thank you so much,
David

**Comment by jdwor** [comment]
Thanks David! I think you might've added 'SIMPLIFY = TRUE' instead of 'SIMPLIFY = FALSE' though. Mind updating that when you get a chance?

Really appreciate your work on this!

**Comment by DavidPayares** [comment]
Thank you again, Jordan! Just updated it.

**Comment by jdwor** [comment]
Fantastic, working like a charm now. Thanks again for putting this package together!
